export const defaultLayout = "normal";

export const naiveThemeOverrides = {
  common: {
    primaryColor: "#316C72FF",
    primaryColorHover: "#316C72E3",
    primaryColorPressed: "#2B4C59FF",
    primaryColorSuppl: "#316C72E3",

    infoColor: "#2080F0FF",
    infoColorHover: "#4098FCFF",
    infoColorPressed: "#1060C9FF",
    infoColorSuppl: "#4098FCFF",

    successColor: "#18A058FF",
    successColorHover: "#36AD6AFF",
    successColorPressed: "#0C7A43FF",
    successColorSuppl: "#36AD6AFF",

    warningColor: "#F0A020FF",
    warningColorHover: "#FCB040FF",
    warningColorPressed: "#C97C10FF",
    warningColorSuppl: "#FCB040FF",

    errorColor: "#D03050FF",
    errorColorHover: "#DE576DFF",
    errorColorPressed: "#AB1F3FFF",
    errorColorSuppl: "#DE576DFF",
  },
};

export const basePermissions = [
  {
    "name": "Qiankun APP",
    "code": "Base",
    "type": "MENU",
    "parentId": null,
    "path": "",
    "redirect": null,
    "icon": "i-fe:grid",
    "component": null,
    "layout": "",
    "keepAlive": null,
    "method": null,
    "description": null,
    "show": true,
    "enable": true,
    "order": 0,
    "children": [{
      "name": "sub-html",
      "code": "sub-html",
      "type": "MENU",
      "parentId": 9,
      "path": "/sub-html",
      "redirect": null,
      "icon": "i-me:awesome",
      "layout": null,
      "keepAlive": null,
      "method": null,
      "description": null,
      "show": true,
      "enable": true,
      "order": 1
    }]
  },
  {
    "name": "主项目路由",
    "code": "Demo",
    "type": "MENU",
    "parentId": null,
    "path": null,
    "redirect": null,
    "icon": "i-fe:grid",
    "component": null,
    "layout": null,
    "keepAlive": null,
    "method": null,
    "description": null,
    "show": true,
    "enable": true,
    "order": 1,
    "children": [
      {
        "name": "home",
        "code": "home",
        "type": "MENU",
        "parentId": null,
        "path": "/home",
        "redirect": null,
        "icon": "i-fe:user",
        "component": "/src/views/home/index.vue",
        "layout": null,
        "keepAlive": null,
        "method": null,
        "description": null,
        "show": true,
        "enable": true,
        "order": 1
      }, {
        "name": "403",
        "code": "403",
        "type": "MENU",
        "parentId": 6,
        "path": "/403",
        "redirect": null,
        "icon": "i-fe:image",
        "component": "/src/views/error-page/403.vue",
        "layout": null,
        "keepAlive": null,
        "method": null,
        "description": null,
        "show": true,
        "enable": true,
        "order": 2
      }, {
        "name": "404",
        "code": "404",
        "type": "MENU",
        "parentId": 6,
        "path": "/404",
        "redirect": null,
        "icon": "i-fe:image",
        "component": "/src/views/error-page/404.vue",
        "layout": "simple",
        "keepAlive": true,
        "method": null,
        "description": null,
        "show": true,
        "enable": true,
        "order": 3
      },
    ]
  },
  {
    code: "ExternalLink",
    name: "外链(可内嵌打开)",
    type: "MENU",
    icon: "i-fe:external-link",
    order: 98,
    enable: true,
    show: true,
    children: [{
      code: "ShowDocs",
      name: "qiankun-template",
      type: "MENU",
      path: "https://firecodes.github.io/qiankun-template/",
      icon: "i-me:docs",
      order: 1,
      enable: true,
      show: true,
    }],
  },
];
